---
title: "EBI_Pipeline_Comparisson"
author: "Sergio Gozalo"
date: "26 de febrero de 2021"
output: 
  github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = setwd("/Users/Usuario/Desktop/Bioinformatica/Practicas/Practicas/Analysis/"))
```


## Loading necessary libraries

```{r}
library("vegan")
library("ggplot2")
library("tidyr")
library("dplyr")
```

## Table reading

```{r}
ebi_go_abundances <- read.table("functional.tables/ERP112966_GO_abundances_v4.1.tsv", header = TRUE, row.names = 1, sep ="\t")
ebi_go_abundances$description <- NULL #Need to remove this column to work
ebi_go_abundances$category <- NULL #Need to remove this column to work
ebi_go_abundances <- t(ebi_go_abundances)

ebi_go.slim_abundances <- read.table("functional.tables/ERP112966_GO-slim_abundances_v4.1.tsv", header = TRUE, row.names = 1, sep ="\t")
ebi_go.slim_abundances$description <- NULL
ebi_go.slim_abundances$category <- NULL
ebi_go.slim_abundances <- t(ebi_go.slim_abundances)

ebi_ipr_abundances <- read.table("functional.tables/ERP112966_IPR_abundances_v4.1.tsv", header = TRUE, row.names = 1, sep ="\t")
ebi_ipr_abundances$description <- NULL
ebi_ipr_abundances$category <- NULL
ebi_ipr_abundances <- t(ebi_ipr_abundances)
```

## Bray-Curtis dissmilarity matrix

```{r}
ebi_go_abundances_bray <- vegdist(ebi_go_abundances, method="bray")

ebi_go.slim_abundances_bray <- vegdist(ebi_go.slim_abundances, method="bray")

ebi_ipr_abundances_bray <- vegdist(ebi_ipr_abundances, method="bray")
```

## Comparisson between the different databases

```{r}
#Plots
plot(ebi_go_abundances_bray, ebi_go.slim_abundances_bray, main = "GO vs GO-SLIM")
abline(0,1)

plot(ebi_go_abundances_bray, ebi_ipr_abundances_bray, main = "GO vs IPR")
abline(0,1)

plot(ebi_go.slim_abundances_bray, ebi_ipr_abundances_bray, main = "GO-SLIM vs IPR")
abline(0,1)

#Mantel test for correlation
mantel(ebi_go_abundances_bray, ebi_go.slim_abundances_bray)
mantel(ebi_go_abundances_bray, ebi_ipr_abundances_bray)
mantel(ebi_go.slim_abundances_bray, ebi_ipr_abundances_bray)
```

Both, plots and mantel test, agree in the very high correlation between the databases.

## Conclusion

All results are very similar, this implies that the pipeline is consistent













