---
title: "Diversity_analysis"
author: "Sergio Gozalo"
date: "5 de abril de 2021"
output: 
  github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = setwd("/Users/Usuario/Desktop/Bioinformatica/Practicas/Practicas/Analysis/"))
```

## Loading necessary libraries

```{r}
library("vegan")
library("ggplot2")
library("tidyr")
library("plyr")
library("dplyr")
library("reshape2")
library("randomcoloR")
```

```{r include=FALSE}
rarefaction<-function(x,subsample=1000, plot=TRUE, color=TRUE, error=FALSE, legend=TRUE, symbol){

        library(vegan)
        x <- as.matrix(x)
	y1<-apply(x, 1, sum)
        rare.data<-x                                   

        select<-unique(sort(c((apply(x, 1, sum)), (seq(0,(max(y1)), by=subsample)), recursive=TRUE)))
        storesummary.e<-matrix(data=NA, ncol=length(rare.data[,1]),nrow=length(select))
        rownames(storesummary.e)<-c(select)
        colnames(storesummary.e)<-rownames(x)
        storesummary.se<-matrix(data=NA, ncol=length(rare.data[,1]),nrow=length(select))
        rownames(storesummary.se)<-c(select)
        colnames(storesummary.se)<-rownames(x)

                for(i in 1:length(select))                      #the for loop
                        {
                        select.c<-select[i]                     #assigns the 'i'th element of select to select.c
                        foo<-rarefy(x,select.c, se=T)           #use whatever vegan fn you want
                storesummary.e[i,]<-foo[1,]
                storesummary.se[i,]<-foo[2,]            
                        }
                storesummary.e<-as.data.frame(storesummary.e)               
                richness.error<<-storesummary.se
                
for (i in 1:(length(storesummary.e)))
{
storesummary.e[,i]<-ifelse(select>sum(x[i,]), NA, storesummary.e[,i])
}

###############plot result################################
if (plot==TRUE)
 {
if(color==TRUE){
plot(select,storesummary.e[,1], xlab="Individuals in Subsample", 
xlim=c(0,max(select)), ylim=c(0, 5+(max(storesummary.e[,1:(length(storesummary.e))], na.rm=TRUE))),
ylab="Mean Species Richness", pch =16, col=2, type="n")

for (j in 1:(length(storesummary.e))){
points(select, storesummary.e[,j], pch=16, col=j+1, type="b", lty=1)}

if(error==TRUE){
for (m in 1:(length(storesummary.e))){
segments(select, storesummary.e[,m]+storesummary.se[,m],select, storesummary.e[,m]-storesummary.se[,m])
}
}
if (legend==TRUE){
legend("bottomright", colnames(storesummary.e), inset=0.05, lty=1, col=1:length(storesummary.e)+1, lwd=2)
}
}
else
{
plot(select,storesummary.e[,1], xlab="Individuals in Subsample", 
xlim=c(0,max(select)), ylim=c(0, 5+(max(storesummary.e[,1:(length(storesummary.e))], na.rm=TRUE))),
ylab="Mean Species Richness", pch =16, col=2, type="n")

for (j in 1:(length(storesummary.e))){
points(select, storesummary.e[,j], type="l", lty=1)}

for (k in 1:(length(storesummary.e))){
symbol<-ifelse(symbol<length(storesummary.e),rep(symbol,2),symbol)
points(as.numeric(rownames(subset(storesummary.e, storesummary.e[,k]==max(storesummary.e[,k],na.rm=TRUE)))), max(storesummary.e[,k],na.rm=TRUE), pch=symbol[k], cex=1.5)}

if(error==TRUE){
for (m in 1:(length(storesummary.e))){
points(select, storesummary.e[,m]+storesummary.se[,m], type="l", lty=2)
points(select, storesummary.e[,m]-storesummary.se[,m], type="l", lty=2)}}

k<-1:(length(storesummary.e))
if (legend==TRUE){
legend("bottomright", colnames(storesummary.e), pch=symbol[k], inset=0.05, cex=1.3)
}
}
}
print("rarefaction by J. Jacobs, last update April 17, 2009")
if(error==TRUE)(print("errors around lines are the se of the iterations, not true se of the means")  )     
list("richness"= storesummary.e, "SE"=richness.error, "subsample"=select)        
 
}
```

#Tables 

```{r}
#ICM
f_kegg_scg <- (read.table("functional.tables/EMOSE-GC_ICM_250bp_KEGG.ko.lengthNorm.SCGnorm.counts.tbl", header = TRUE, sep = "\t", row.names = 1))

f_kegg_scgt <- t(f_kegg_scg)

f_kegg_mgn <- (read.table("functional.tables/EMOSE-GC_ICM_250bp_KEGG.ko.lengthNorm.metaGsizeNorm.counts.tbl", header = TRUE, sep = "\t", row.names = 1))

f_kegg_mgnt <- t(f_kegg_scg)

icm_cog_scg <- (read.table("functional.tables/EMOSE-GC_ICM_250bp_COG.lengthNorm.SCGnorm.counts.tbl", header = TRUE, sep = "\t", row.names = 1))

icm_pfam_scg <- (read.table("functional.tables/EMOSE-GC_ICM_250bp_pfam.lengthNorm.SCGnorm.counts.tbl", header = TRUE, sep = "\t", row.names = 1))

otu_mitags <- (read.delim("functional.tables/otu_table97.txt", header = TRUE, sep = "\t"))
otu_mitags$OTUId <- NULL
otu_mitags <- t(otu_mitags)


```

## Richness MiTags

```{r}
otu_mitags_ss <- rrarefy(otu_mitags, min(rowSums(otu_mitags)))
richness <- estimateR(otu_mitags_ss)
richness
```

## Rarefaction MiTags

```{r}
otu_rare <- rarefaction(otu_mitags_ss)
```


## Rarecurve MiTags

```{r}
otu_rcurve <- rarecurve(otu_mitags_ss)
```

## Acumulation curve MiTags

```{r}
otu_acc <- specaccum(otu_mitags_ss, method = "exact", permutations = 1000)
plot(otu_acc)
```

## Richness KEGG

```{r}

f_keg <- as.data.frame(f_kegg_scg)
f_keg[,1:50] <- sapply(f_keg[, c(1:50)], as.integer)
length(f_keg)
richness <- estimateR(f_keg)


f_kegt <- as.data.frame(f_kegg_scgt)
f_kegt[,1:6965] <- sapply(f_kegt[, c(1:6965)], as.integer)
length(f_kegt)
richnesst <- estimateR(f_kegt)
```

## Rarefaction KEGG

### SCG + trans

```{r}
kegg_ss <- rrarefy(f_kegt, min(rowSums(f_kegt)))
kegg_rare <- rarefaction(kegg_ss)
```

### SCG + no trans

```{r}
# kegg_ss <- rrarefy(f_keg, min(rowSums(f_keg))) 
# No rrarefy porque l minimo es 0

kegg_rare <- rarefaction(f_keg)
```


```{r}

f_kegg_mgn <- as.data.frame(f_kegg_mgn)
f_kegg_mgn[,1:50] <- sapply(f_kegg_mgn[, c(1:50)], as.integer)
length(f_kegg_mgn)
richness <- estimateR(f_kegg_mgn)


f_kegg_mgnt <- as.data.frame(f_kegg_mgnt)
f_kegg_mgnt[,1:6965] <- sapply(f_kegg_mgnt[, c(1:6965)], as.integer)
length(f_kegg_mgnt)
richnesst <- estimateR(f_kegt)
```


### mgn + trans

```{r}
kegg_ss <- rrarefy(f_kegg_mgnt, min(rowSums(f_kegg_mgnt)))
kegg_rare <- rarefaction(kegg_ss)
```


### mgn + no trans

```{r}
# kegg_ss <- rrarefy(f_kegg_mgn, min(rowSums(f_kegg_mgn)))
#kegg_rare <- rarefaction(f_kegg_mgn)
```

