---
title: "pruebas"
author: "Sergio Gozalo"
date: "26 de mayo de 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = setwd("/Users/Usuario/Desktop/Bioinformatica/Practicas/Practicas/Analysis/"))
```

## Loading necessary libraries

```{r include=FALSE}
library("vegan")
library("ggplot2")
library("tidyr")
library("dplyr")
library("recluster")
library(compositions)
library(zCompositions)
```

```{r}
icm_kegg_meta <- t(read.table("functional.tables/EMOSE-GC_ICM_250bp_KEGG.ko.lengthNorm.metaGsizeNorm.counts.tbl", header = TRUE, sep = "\t", row.names = 1))
icm_kegg_scg <- t(read.table("functional.tables/EMOSE-GC_ICM_250bp_KEGG.ko.lengthNorm.SCGnorm.counts.tbl", header = TRUE, sep = "\t", row.names = 1))
```

```{r}
icm_kegg_meta <- as.data.frame(icm_kegg_meta)
otu.tab.simple.gbm<-cmultRepl(t(icm_kegg_meta), output = "p-counts") 
```

```{r}
f_kegt <- as.data.frame(f_kegg_scgt)
f_kegt[,1:6965] <- sapply(f_kegt[, c(1:6965)], as.integer)

kegg_ss <- rrarefy(f_kegt, mean(rowSums(f_kegt))) # Usar media en vez de min
# Probar multiplicar *1000
kegg_acc2 <- specaccum(kegg_ss, method = "exact", permutations = 1000)
plot(kegg_acc2)
```

